version: '3.6'

services:
  amule:
    container_name: amule
    build:
      context: builders/amule
    image: user/amule
    ports:
      - "4662:4662/tcp"
      - "4665:4665/udp"
      - "4672:4672/udp"
      - "4711:4711/tcp"
    volumes:
      - /mnt/amuledock/Incoming:/var/lib/amule/.aMule/Incoming
      - /mnt/amuledock/Temp:/var/lib/amule/.aMule/Temp
    environment:
      - ECPASSWORD=alcocer.1234
      - WEBPASSWORD=alcocer.1234
    restart: unless-stopped


